### ISSUE TITLE
[QUESTION]: Design-first approach with Screenplay pattern

### ISSUE THREAD

**Issue by iminder-singh** [q2ebanking/boa-constrictor#269]
### What is your question?

Hi

I'm really excited to start implementing the Screenplay pattern for both UI and API testing at my organisation. 

For APIs, we're taking a design-first approach, so I was wondering if you have any recommendations or best approaches to do this with the screenplay pattern.

I have the idea of using Nswag or something similar to generate the client and models from the Open API spec and then use these as abilities in the tests. 

All thoughts and suggestions are welcome!

Thanks.

### Commitments

- [X] I agree to follow Boa Constrictor's [Code of Conduct](https://q2ebanking.github.io/boa-constrictor/contributing/code-of-conduct/).

**Comment by AutomationPanda** [comment]
Hi @iminder-singh. I'm sorry for the delayed reply. I'm not sure what to recommend because I'm not sure how Screenplay Pattern would work together with OpenAPI. To me, these seem like two different concerns. Screenplay is a design pattern for making automated interactions, while OpenAPI is a standard for defining APIs. Screenplay interactions can call APIs, but I'm not sure how that would do anything with OpenAPI specs.
