### ISSUE TITLE
Using REST API to set up test via code seams 

### ISSUE THREAD

**Issue by bottbott** [q2ebanking/boa-constrictor#74]
Hi there!

Would there be a recommendation for or against utilizing and creating Abilities/Interactions for the Actor to use RestSharp to set up the environment for a test? I would imagine the use case for the current implementation is for testing the Service/API layer, but it seems to me that it would be OK to use it for setup as well. 

There are test automation approaches that encourage the use of code seams to write more efficient tests by setting up the test conditions thru the Service layer and then finish your test in the UI. For example... If I want to test removing a product from my Shopping Basket...

1. Navigate to web site.
2. Search for an item.
3. Add it to my cart.
4. Go to my cart.
5. Remove the item from my cart.

Steps 1-4 can all be bypassed (and tested in separate test cases as necessary) by using an API to directly add a product to the cart and then navigating directly to the cart to complete the UI automation of step 5. 

Beyond that - are there any Examples kicking around of the RestSharp classes being used?

**Comment by AndyLPK247** [comment]
Great questions. Yes, there is a clean way to do this. No, we unfortunately don’t have public examples yet. We plan to write docs in the coming weeks. I’ll share an example here tomorrow.

**Comment by pl-aknight** [comment]
The simplest way to make RestSharp calls is by using the `CallRestApi` Ability:

```csharp
Actor.Can(
    CallRestApi.At("https://yoursite.com")
        .DumpingRequestsTo("/path/to/request/dumpdir")
        .DumpingDownloadsTo("/path/to/download/dumpdir")
);

TAnswer response = Actor.Calls(Rest.Request<TAnswer>(yourRestRequestObject));
byte[] download = Actor.Calls(Rest.Download(anotherRestRequestObject));
```

The dump directories are optional. I recommend using them so that debugging failures is easier.

(Upon reviewing this code, I realized that we should enable direct injection of the `RestClient` object into the Ability. See #75.)

If you need to handle multiple `RestClient` objects (meaning that you hit multiple base URLs), then I recommend creating custom Abilities for each as subclasses of `AbstractRestSharpAbility`. `CallRestApi` works when you need to handle only one.

**Comment by pl-aknight** [comment]
@bottbott, in your example, I'd recommend writing a new Task that uses Boa Constrictor's RestSharp calls as shown in the previous comment to handle steps 1-4.

**Comment by AndyLPK247** [comment]
I'm closing this issue because I believe the question has been answered.
