### ISSUE TITLE
GitHub Action to publish NuGet packages reports an error

### ISSUE THREAD

**Issue by AndyLPK247** [q2ebanking/boa-constrictor#92]
Recent runs of the GitHub Action that publishes the Boa Constrictor NuGet package have reported errors. Thankfully, it appears that packages still get published successfully, but we should still resolve the error.

Log: https://github.com/q2ebanking/boa-constrictor/actions/runs/775107523

**Comment by AndyLPK247** [comment]
This issue relates to this one:
https://github.com/brandedoutcast/publish-nuget/issues/58

**Comment by AndyLPK247** [comment]
Unfortunately, removing `NUGET_SOURCE` from the action's YML file didn't make the error message go away.

**Comment by pl-aknight** [comment]
A potential fix is ready to merge: https://github.com/brandedoutcast/publish-nuget/issues/58

**Comment by AutomationPanda** [comment]
I updated the Boa.Constrictor project to do embedded debugging:

```xml
<DebugType>embedded</DebugType>
```

This removes the need for a symbols package, so I removed it. Symbols packages also are currently incompatible with NuGet package READMEs.

I updated our GitHub Action so that it no longer publishes a symbols package. This issue is no longer a problem.
